openapi: 3.1.0
info:
  title: Work app
  version: 1.0.0
  license:
    name: Apache 2.0
    url: http://www.org/license/LICENSE-2.0.html
  description: This is a documentation of contacts app

tags:
  - name: Contacts
    description: Operations about contacts.
  - name: Authentication
    description: Authentication operations.

servers:
  - url: http://localhost:3000
  - url: 

paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml

  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml

  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml

  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml

  /auth/reset-pwd: 
    post:
      $ref: ../swagger/paths/auth/resetpwd.yaml

  /auth/send-reset-email:
    post:
      $ref: ../swagger/paths/auth/sendresetemail.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT